Revert "Fixed the build error: Error CS8103 Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals"
This reverts commit 6335821264a2dbbca5a3e36e050b91f9f0acbe56.